---
title: "Park rural comparisons"
output: pdf
---

import here and avoid next 5 steps:
```{r}
rm(list=ls())
all_sites_merged <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/all_sites_merged.csv")
```


1. import data
```{r}
rm(list=ls())
STGA <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRSTGA.csv")
FRIE <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRFRIE.csv")
SEEP <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRSEEP.csv")
HOCH <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRHOCH.csv")
clouds <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/complete_cloud_cover.csv")
```

2.
```{r}
library(dplyr)
all_sites <- bind_rows(STGA, FRIE, SEEP, HOCH)
```

3. merging with cloud cover:
```{r}
clouds$datetime_clean <- ifelse(
  grepl(":", clouds$datetime),  # has time
  clouds$datetime,              # keep as is
  paste(clouds$datetime, "0:00") # add midnight time
)

clouds$datetime_posix <- as.POSIXct(clouds$datetime_clean, 
                                                 format = "%m/%d/%y %H:%M")
clouds <- clouds[, !names(clouds) %in% c("datetime_clean", "datetime")]
```

4. changing datetime of all_sites:
```{r}
all_sites$datetime <- as.POSIXct(all_sites$datetime, 
                                      format = "%Y-%m-%d %H:%M:%S")
```
merging:
```{r}
all_sites_merged <- merge(all_sites, clouds, 
                         by.x = "datetime", 
                         by.y = "datetime_posix", 
                         all.x = TRUE)

all_sites_merged <- all_sites_merged[order(all_sites_merged$station_id, 
                                          all_sites_merged$datetime), ]
```


fit a model:
```{r}
comp <- lm(cooling_rate ~ station_id * phenophase * WindSpeed_Avg_m_s * interpolated_V_N, 
           data = all_sites_merged[all_sites_merged$time_after_sunset <= 4, ])
summary(comp)
```

pairwise comparisons
WHOLE YEAR
```{r}
aov_res <- aov(cooling_rate ~ station_id * phenophase * interpolated_V_N, 
               data = all_sites_merged[all_sites_merged$time_after_sunset <= 4, ])

TukeyHSD(aov_res, "station_id")
```

LEAFLESS
```{r}
aov_res <- aov(cooling_rate ~ station_id * interpolated_V_N, 
               data = all_sites_merged[all_sites_merged$time_after_sunset <= 4 & 
                                      all_sites_merged$phenophase == "leafless", ])

TukeyHSD(aov_res, "station_id")
```
FULL CANOPY
```{r}
aov_res <- aov(cooling_rate ~ station_id * interpolated_V_N, 
               data = all_sites_merged[all_sites_merged$time_after_sunset <= 4 & 
                                      all_sites_merged$phenophase == "full_canopy", ])

TukeyHSD(aov_res, "station_id")
```


```{r}
plot(comp)  # check residuals
```


