---
title: "Air temperature in HW new plots"
output: pdf_document
date: "2025-08-30"
---

import data
```{r}
rm(list=ls())
FRSTGA <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRSTGA.csv")
FRKART <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRKART.csv")
FRINST <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRINST.csv")
FRFRIE <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRFRIE.csv")
FRMESS <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRMESS.csv")
FRUNIK <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRUNIK.csv")
FRSEEP <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRSEEP.csv")
FRBETZ <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRBETZ.csv")
FRHOCH <- read.csv("/Users/teodorica/Downloads/papr/R/atmosfr/sites/FRHOCH.csv")
```

```{r}
library(dplyr)
FRSTGAhwAugust <- FRSTGA %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRKARThwAugust <- FRKART %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRINSThwAugust <- FRINST %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRFRIEhwAugust <- FRFRIE %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRMESShwAugust <- FRMESS %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRUNIKhwAugust <- FRUNIK %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRSEEPhwAugust <- FRSEEP %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRBETZhwAugust <- FRBETZ %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRHOCHhwAugust <- FRHOCH %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
```

only mean air temperatures observations:
```{r}
FRSTGA_means <- FRSTGAhwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRKART_means <- FRKARThwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRINST_means <- FRINSThwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRFRIE_means <- FRFRIEhwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRMESS_means <- FRMESShwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRUNIK_means <- FRUNIKhwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRSEEP_means <- FRSEEPhwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRBETZ_means <- FRBETZhwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
FRHOCH_means <- FRHOCHhwAugust %>%
  group_by(time_after_sunset) %>%
  summarize(mean_ta = mean(ta, na.rm = TRUE))
```


graph version with TRANSPARENT lines:
```{r}
pdf("/Users/teodorica/Downloads/papr/R/atmosfr/hw/allsites_airtemp_88.pdf", width = 7, height = 5, pointsize = 10)
par(mar = c(4, 4, 3, 1), bg = "white")

y_range_combined <- c(18, 28)  

plot(0, 0, type = "n",
     xlim = c(0, 8), ylim = y_range_combined,
     xlab = "Hour After Sunset", ylab = "Air Temperature (°C)",
     main = "Mean Air Temperatures 13-24th August 2023",
     cex.main = 1.3, las = 1,
     xaxt = "n", yaxt = "n") 

box(col = "black")

axis(1, at = 0:8, labels = 0:8)
axis(2, at = seq(18, 28, by = 1), las = 1)

grid(col = "gray90", lty = "dotted")

# only plot up to hour 8
filter_data <- function(data_frame) {
  return(data_frame[data_frame$time_after_sunset <= 8, ])
}

FRSTGA_filtered <- filter_data(FRSTGA_means)
FRHOCH_filtered <- filter_data(FRHOCH_means)
FRFRIE_filtered <- filter_data(FRFRIE_means)
FRSEEP_filtered <- filter_data(FRSEEP_means)
FRKART_filtered <- filter_data(FRKART_means)
FRINST_filtered <- filter_data(FRINST_means)
FRUNIK_filtered <- filter_data(FRUNIK_means)
FRMESS_filtered <- filter_data(FRMESS_means)
FRBETZ_filtered <- filter_data(FRBETZ_means)

# main colors
darkgreen_color <- "darkgreen"    # STGA
darksalmon_color <- "darksalmon"  # FRIE
cornflowerblue_color <- "cornflowerblue"  # SEEP
green3_color <- "green3"          # HOCH

# transparent colors for built-up areas (50% transparency)
darkgreen_transparent <- adjustcolor(darkgreen_color, alpha.f = 0.65)
darksalmon_transparent <- adjustcolor(darksalmon_color, alpha.f = 0.65)
cornflowerblue_transparent <- adjustcolor(cornflowerblue_color, alpha.f = 0.65)

# KART stga
if (nrow(FRKART_filtered) > 0) {
  lines(FRKART_filtered$time_after_sunset, FRKART_filtered$mean_ta, 
        col = darkgreen_transparent, lwd = 2, lty = 2)
  points(FRKART_filtered$time_after_sunset, FRKART_filtered$mean_ta, 
         col = darkgreen_transparent, pch = 17, cex = 1.2)  # Triangle symbol
}

# INST stga
lines(FRINST_filtered$time_after_sunset, FRINST_filtered$mean_ta, 
      col = darkgreen_transparent, lwd = 1.5, lty = 3)
points(FRINST_filtered$time_after_sunset, FRINST_filtered$mean_ta, 
       col = darkgreen_transparent, pch = 15, cex = 1)  # Square symbol

# MESS frie
lines(FRMESS_filtered$time_after_sunset, FRMESS_filtered$mean_ta, 
      col = darksalmon_transparent, lwd = 1.5, lty = 3)
points(FRMESS_filtered$time_after_sunset, FRMESS_filtered$mean_ta, 
       col = darksalmon_transparent, pch = 17, cex = 1)  # Triangle symbol

# UNIK frie
lines(FRUNIK_filtered$time_after_sunset, FRUNIK_filtered$mean_ta, 
      col = darksalmon_transparent, lwd = 1.5, lty = 2)
points(FRUNIK_filtered$time_after_sunset, FRUNIK_filtered$mean_ta, 
       col = darksalmon_transparent, pch = 15, cex = 1)  # Square symbol

# BETZ seep
lines(FRBETZ_filtered$time_after_sunset, FRBETZ_filtered$mean_ta, 
      col = cornflowerblue_transparent, lwd = 1.5, lty = 2)
points(FRBETZ_filtered$time_after_sunset, FRBETZ_filtered$mean_ta, 
       col = cornflowerblue_transparent, pch = 15, cex = 1)  # Square symbol

# PARKS
lines(FRSTGA_filtered$time_after_sunset, FRSTGA_filtered$mean_ta, col = darkgreen_color, lwd = 2.5)
lines(FRHOCH_filtered$time_after_sunset, FRHOCH_filtered$mean_ta, col = green3_color, lwd = 2.5)  
lines(FRFRIE_filtered$time_after_sunset, FRFRIE_filtered$mean_ta, col = darksalmon_color, lwd = 2.5)
lines(FRSEEP_filtered$time_after_sunset, FRSEEP_filtered$mean_ta, col = cornflowerblue_color, lwd = 2.5)

# PARKS
points(FRSTGA_filtered$time_after_sunset, FRSTGA_filtered$mean_ta, col = darkgreen_color, pch = 16, cex = 1.2)
points(FRHOCH_filtered$time_after_sunset, FRHOCH_filtered$mean_ta, col = green3_color, pch = 16, cex = 1.2)
points(FRFRIE_filtered$time_after_sunset, FRFRIE_filtered$mean_ta, col = darksalmon_color, pch = 16, cex = 1.2)
points(FRSEEP_filtered$time_after_sunset, FRSEEP_filtered$mean_ta, col = cornflowerblue_color, pch = 16, cex = 1.2)

legend("topright", 
       legend = c("Parks/Rural Site:", "STGA", "FRIE", "SEEP", "HOCH",
                  "", "Built-up Areas:", "KART", "INST", "MESS", "UNIK", "BETZ"),
       col = c(NA, darkgreen_color, darksalmon_color, cornflowerblue_color, green3_color,
               NA, NA, darkgreen_transparent, darkgreen_transparent, 
               darksalmon_transparent, darksalmon_transparent, cornflowerblue_transparent),
       pch = c(NA, 16, 16, 16, 16, NA, NA, 17, 15, 17, 15, 15),
       lty = c(NA, 1, 1, 1, 1, NA, NA, 2, 3, 3, 2, 2),
       lwd = c(NA, 2.5, 2.5, 2.5, 2.5, NA, NA, 1.8, 1.8, 1.8, 1.8, 1.8),
       cex = 0.75,
       bg = "white")

dev.off()
```