---
title: "CR new version HW"
output: pdf
---

skip first five step if importing 
* datasets include mean CR over the 12 heatwave days for 0-8 hour after sunset
```{r}
rm(list=ls())
FRSTGA_data <- read.csv("FRSTGA_data.csv")
FRSEEP_data <- read.csv("FRSEEP_data.csv")
FRFRIE_data <- read.csv("FRFRIE_data.csv")
FRHOCH_data <- read.csv("FRHOCH_data.csv")
```

1. importing data
```{r}
rm(list=ls())
FRHOCH <- read.csv("/Users/teodorica/Downloads/thesonja/R/R for the thesis/sites/FRHOCH.csv")
FRSTGA <- read.csv("/Users/teodorica/Downloads/thesonja/R/R for the thesis/sites/FRSTGA.csv")
FRSEEP <- read.csv("/Users/teodorica/Downloads/thesonja/R/R for the thesis/sites/FRSEEP.csv")
FRBETZ <- read.csv("/Users/teodorica/Downloads/thesonja/R/R for the thesis/sites/FRBETZ.csv")
FRFRIE <- read.csv("/Users/teodorica/Downloads/thesonja/R/R for the thesis/sites/FRFRIE.csv")
```

2. the 12 days - 13-24.08.2025
```{r}
library(dplyr)
FRSEEPhwAugust <- FRSEEP %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRSTGAhwAugust <- FRSTGA %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRFRIEhwAugust <- FRFRIE %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
FRHOCHhwAugust <- FRHOCH %>%
  filter(datetime >= "2023-08-13 00:00:00" & 
         datetime <= "2023-08-24 23:00:00")
```

3. midnight
```{r}
FRSEEPhwAugust$datetime <- as.POSIXct(
  ifelse(nchar(FRSEEPhwAugust$datetime) == 10, 
         paste(FRSEEPhwAugust$datetime, "00:00:00"), 
         FRSEEPhwAugust$datetime),
  format = "%Y-%m-%d %H:%M:%S"
)
FRSTGAhwAugust$datetime <- as.POSIXct(
  ifelse(nchar(FRSTGAhwAugust$datetime) == 10, 
         paste(FRSTGAhwAugust$datetime, "00:00:00"), 
         FRSTGAhwAugust$datetime),
  format = "%Y-%m-%d %H:%M:%S"
)
FRFRIEhwAugust$datetime <- as.POSIXct(
  ifelse(nchar(FRFRIEhwAugust$datetime) == 10, 
         paste(FRFRIEhwAugust$datetime, "00:00:00"), 
         FRFRIEhwAugust$datetime),
  format = "%Y-%m-%d %H:%M:%S"
)
FRHOCHhwAugust$datetime <- as.POSIXct(
  ifelse(nchar(FRHOCHhwAugust$datetime) == 10, 
         paste(FRHOCHhwAugust$datetime, "00:00:00"), 
         FRHOCHhwAugust$datetime),
  format = "%Y-%m-%d %H:%M:%S"
)
```

4. mean cooling rates
```{r}
calculate_hourly_cooling_rates <- function(data, time_after_sunset_col, cooling_col, max_hours = 8) {
  # Filter for only the first max_hours after sunset using time_after_sunset column
  filtered_data <- data[data[[time_after_sunset_col]] <= max_hours, ]
  
  # Get unique rounded hours from time_after_sunset for grouping
  unique_hours <- sort(unique(round(filtered_data[[time_after_sunset_col]])))
  unique_hours <- unique_hours[unique_hours <= max_hours]  # Ensure we only include hours up to max_hours
  
  # Initialize results dataframe
  results <- data.frame(
    hour = numeric(),
    mean_cooling = numeric(),
    se_cooling = numeric(),
    n = numeric()
  )
  
  # For each hour
  for (h in unique_hours) {
    # Find cooling values for this hour (rounded from time_after_sunset)
    hour_data <- filtered_data[round(filtered_data[[time_after_sunset_col]]) == h, ]
    cooling_values <- hour_data[[cooling_col]]
    cooling_values <- cooling_values[!is.na(cooling_values)]
    
    # Calculate stats if we have data
    if (length(cooling_values) > 0) {
      mean_val <- mean(cooling_values)
      # Calculate SE if we have multiple values
      if (length(cooling_values) > 1) {
        se_val <- sd(cooling_values) / sqrt(length(cooling_values))
      } else {
        se_val <- NA  # Better to use NA than 0 for missing SE
      }
      
      # Add to results
      results <- rbind(results, data.frame(
        hour = h,
        mean_cooling = mean_val,
        se_cooling = se_val,
        n = length(cooling_values)
      ))
    }
  }
  
  return(results)
}
```

5. applying the function:
```{r}
FRSTGA_data <- calculate_hourly_cooling_rates(
  data = FRSTGAhwAugust,  
  time_after_sunset_col = "time_after_sunset",
  cooling_col = "cooling_rate",
  max_hours = 8
)
FRHOCH_data <- calculate_hourly_cooling_rates(
  data = FRHOCHhwAugust, 
  time_after_sunset_col = "time_after_sunset",
  cooling_col = "cooling_rate",
  max_hours = 8
)
FRFRIE_data <- calculate_hourly_cooling_rates(
  data = FRFRIEhwAugust,  
  time_after_sunset_col = "time_after_sunset",
  cooling_col = "cooling_rate",
  max_hours = 8
)
FRSEEP_data <- calculate_hourly_cooling_rates(
  data = FRSEEPhwAugust,
  time_after_sunset_col = "time_after_sunset",
  cooling_col = "cooling_rate",
  max_hours = 8
)
```

PLOTTING
dodging/plotting function
```{r}
plot_cooling_rates <- function(FRSTGA_data, FRHOCH_data, FRFRIE_data, FRSEEP_data, 
                              y_min = 0, y_max = 3.5, offset = 0.15) {  
  par(mar = c(5, 5, 4, 2))
  
  # empty plot
  plot(0, 0, type = "n",
       xlim = c(-0.5, 8.5),
       ylim = c(y_min, y_max),  
       xlab = "", ylab = "",
       main = "Hourly Cooling Rates for Different Parks",
       cex.main = 1.2, axes = FALSE) 
    box(col = "black")
    grid(col = "lightgray", lty = "dotted")
  
  # reference line at zero
  abline(h = 0, lty = 2, col = "gray50", lwd = 1.5)
  
  colors <- c("darkgreen", "darksalmon", "cornflowerblue", "green3")
  point_types <- c(16, 18, 15, 17)  # Different point shapes
  
  # larger offsets for better separation
  offset1 = offset * 2
  offset2 = offset * 0.667
  offset3 = offset * 0.667
  offset4 = offset * 2
  
  # lines and points for each park with  dodging
  # FRSTGA
  if (!is.null(FRSTGA_data) && nrow(FRSTGA_data) > 0) {
    lines(FRSTGA_data$hour - offset1, FRSTGA_data$mean_cooling, 
          col = colors[1], lwd = 2)
    points(FRSTGA_data$hour - offset1, FRSTGA_data$mean_cooling, 
           col = colors[1], pch = point_types[1], cex = 1.3, bg = "white")
    arrows(FRSTGA_data$hour - offset1, FRSTGA_data$mean_cooling - FRSTGA_data$se_cooling,
           FRSTGA_data$hour - offset1, FRSTGA_data$mean_cooling + FRSTGA_data$se_cooling,
           angle = 90, code = 3, length = 0.05, col = colors[1], lwd = 1.5)
  }
  
  # FRFRIE
  if (!is.null(FRFRIE_data) && nrow(FRFRIE_data) > 0) {
    lines(FRFRIE_data$hour - offset2, FRFRIE_data$mean_cooling, 
          col = colors[2], lwd = 2)
    points(FRFRIE_data$hour - offset2, FRFRIE_data$mean_cooling, 
           col = colors[2], pch = point_types[2], cex = 1.3, bg = "white")
    arrows(FRFRIE_data$hour - offset2, FRFRIE_data$mean_cooling - FRFRIE_data$se_cooling,
           FRFRIE_data$hour - offset2, FRFRIE_data$mean_cooling + FRFRIE_data$se_cooling,
           angle = 90, code = 3, length = 0.05, col = colors[2], lwd = 1.5)
  }
  
  # FRSEEP
  if (!is.null(FRSEEP_data) && nrow(FRSEEP_data) > 0) {
    lines(FRSEEP_data$hour + offset3, FRSEEP_data$mean_cooling, 
          col = colors[3], lwd = 2)
    points(FRSEEP_data$hour + offset3, FRSEEP_data$mean_cooling, 
           col = colors[3], pch = point_types[3], cex = 1.3, bg = "white")
    arrows(FRSEEP_data$hour + offset3, FRSEEP_data$mean_cooling - FRSEEP_data$se_cooling,
           FRSEEP_data$hour + offset3, FRSEEP_data$mean_cooling + FRSEEP_data$se_cooling,
           angle = 90, code = 3, length = 0.05, col = colors[3], lwd = 1.5)
  }
  
  # FRHOCH
  if (!is.null(FRHOCH_data) && nrow(FRHOCH_data) > 0) {
    lines(FRHOCH_data$hour + offset4, FRHOCH_data$mean_cooling, 
          col = colors[4], lwd = 2)
    points(FRHOCH_data$hour + offset4, FRHOCH_data$mean_cooling, 
           col = colors[4], pch = point_types[4], cex = 1.3, bg = "white")
    arrows(FRHOCH_data$hour + offset4, FRHOCH_data$mean_cooling - FRHOCH_data$se_cooling,
           FRHOCH_data$hour + offset4, FRHOCH_data$mean_cooling + FRHOCH_data$se_cooling,
           angle = 90, code = 3, length = 0.05, col = colors[4], lwd = 1.5)
  }
  
  # clean x-axis
  axis(1, at = 0:8, labels = TRUE, lwd = 1)
  mtext("Hour After Sunset", side = 1, line = 3, cex = 1.1)
  
  # clean y-axis with labels - starting from 0
  y_seq <- seq(y_min, y_max, by = 0.5)
  axis(2, at = y_seq, labels = format(y_seq, nsmall = 1), las = 1, lwd = 1)
  
  # y-axis label as a separate element
  mtext(expression(paste("Cooling Rate (°C/h)")), 
        side = 2, line = 3.2, cex = 1.1)
  
  legend("topright", 
         legend = c("STGA", "FRIE", "SEEP", "HOCH"),
         col = colors, 
         pch = point_types,
         lwd = 2, 
         pt.cex = 1.2,
         bty = "o",
         bg = "white",
         box.col = "black",
         cex = 0.9,
         inset = 0.02)
}
```

the actual plotting
```{r}
pdf("/Users/teodorica/Downloads/papr/R/atmosfr/hw/mean_CR_parks/CR_hw_parks_averaged.pdf", width = 7, height = 5, pointsize = 10)
all_data <- rbind(
  cbind(FRSTGA_data, park = "STGA"),
  cbind(FRHOCH_data, park = "HOCH"),
  cbind(FRFRIE_data, park = "FRIE"),
  cbind(FRSEEP_data, park = "SEEP")
)

y_min <- min(all_data$mean_cooling - all_data$se_cooling, na.rm = TRUE)
y_max <- max(all_data$mean_cooling + all_data$se_cooling, na.rm = TRUE)

# add a bit of padding
y_min <- floor(y_min * 2) / 2  
y_max <- ceiling(y_max * 2) / 2 

# Create the plot
plot_cooling_rates(
  FRSTGA_data = FRSTGA_data,
  FRHOCH_data = FRHOCH_data,
  FRFRIE_data = FRFRIE_data,  
  FRSEEP_data = FRSEEP_data,
  y_min = 0,
  y_max = y_max,
  offset = 0.1  # control the amount of dodging
)
dev.off()
```